apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: safemapsbackend
          image: itsayushpandey/safemapfrontend:v3
          ports:
            - containerPort: 3000
---
