apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: safemapsbackend
          image: itsayushpandey/safemapbackend
          ports:
            - containerPort: 3000
---
